### ISSUE TITLE
version:2023120500 IndexError: list index out of range

### ISSUE THREAD

**Issue by talkouki89** [Nyanm/Saccharomyces-cerevisiae#10]
> [INFO] FileHandler.encoding = utf-8
[INFO] TEST_MODE on
[INFO] config.cfg load complete.
map size  :2000
card num  :A59A6D749842E3B8
db dir    :C:/ArcadeHDD/Network/SDVX/savedata/sdvx@asphyxia.db
game dir  :C:/ArcadeHDD/SDVX/EXCEEDGEAR/contents/data
output    :C:/ArcadeHDD/SDVX
skin name :gen6
language  :ZH
is init   :True
version   :2023120500
[INFO] Load aka_db, level_table, search_db from ./data
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from genre import packet
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\genre\__init__.py", line 1, in <module>
    from genre import gen5, gen6
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\genre\gen6\__init__.py", line 1, in <module>
    from genre.gen6 import main
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\genre\gen6\main.py", line 12, in <module>
    from parse import npdb
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\parse\__init__.py", line 2, in <module>
    from .asp import asp
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\parse\asp.py", line 157, in <module>
    asp = ASPParser(db_dir=cfg.db_dir, map_size=cfg.map_size, card_num=cfg.card_num)
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-mod\parse\asp.py", line 67, in __init__
    self.music_map[cur_index][0] = True
IndexError: list index out of range

**Comment by LyceenAiro** [comment]
because now the game's tracks have exceeded 2000 songs
increase the value of `map size` in config.cfg
try changing it to 2100 or higher

**Comment by talkouki89** [comment]
> because now the game's tracks have exceeded 2000 songs
> 
> increase the value of `map size` in config.cfg
> 
> try changing it to 2100 or higher

可以做使用了
但生成图片会出现下列错误

libpng warning: iCCP: known incorrect sRGB profile
[WARNING] Something wrong happens in the plot function, only will the text message be returned.
Traceback (most recent call last):
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\main.py", line 410, in plot_b50
    std_profile = generate_std_profile(profile, vol_force)
  File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\tools.py", line 303, in generate_std_profile
    profile_y, profile_x, chn = profile_box.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by LyceenAiro** [comment]
> > because now the game's tracks have exceeded 2000 songs
> > 
> > increase the value of `map size` in config.cfg
> > 
> > try changing it to 2100 or higher
> 
> 可以做使用了
> 但生成图片会出现下列错误
> 
> libpng warning: iCCP: known incorrect sRGB profile
> [WARNING] Something wrong happens in the plot function, only will the text message be returned.
> Traceback (most recent call last):
>   File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\main.py", line 410, in plot_b50
>     std_profile = generate_std_profile(profile, vol_force)
>   File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\tools.py", line 303, in generate_std_profile
>     profile_y, profile_x, chn = profile_box.shape
> AttributeError: 'NoneType' object has no attribute 'shape'

你是第一次使用这个软件吗，现版本这个软件使用游戏资源库生成的皮肤文件和旧版本生成的文件大部分都不一致导致不能正常使用，想要正常生成图片需要指定一个别人在旧版本生成并使用正常的皮肤包或者自己修复皮肤包中的文件，修复工作当然要看着源码来且十分困难，最好去找一个已经正常使用这个软件的朋友拿一个皮肤包或者通过我的主页联系我也可以，我没有办法修复生成的问题，只有这个解决方法

**Comment by talkouki89** [comment]
> > > because now the game's tracks have exceeded 2000 songs
> > > 
> > > increase the value of `map size` in config.cfg
> > > 
> > > try changing it to 2100 or higher
> > 
> > 可以做使用了
> > 但生成图片会出现下列错误
> > 
> > libpng warning: iCCP: known incorrect sRGB profile
> > [WARNING] Something wrong happens in the plot function, only will the text message be returned.
> > Traceback (most recent call last):
> >   File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\main.py", line 410, in plot_b50
> >     std_profile = generate_std_profile(profile, vol_force)
> >   File "C:\ArcadeHDD\SDVX\TOOLS\Saccharomyces-cerevisiae-master\genre\gen6\tools.py", line 303, in generate_std_profile
> >     profile_y, profile_x, chn = profile_box.shape
> > AttributeError: 'NoneType' object has no attribute 'shape'
> 
> 你是第一次使用这个软件吗，现版本这个软件使用游戏资源库生成的皮肤文件和旧版本生成的文件大部分都不一致导致不能正常使用，想要正常生成图片需要指定一个别人在旧版本生成并使用正常的皮肤包或者自己修复皮肤包中的文件，修复工作当然要看着源码来且十分困难，最好去找一个已经正常使用这个软件的朋友拿一个皮肤包或者通过我的主页联系我也可以，我没有办法修复生成的问题，只有这个解决方法

好的 我在联系你 感谢您
