### ISSUE TITLE
XCD Diff Not Supported

### ISSUE THREAD

**Issue by Derrick97** [Nyanm/Saccharomyces-cerevisiae#3]
When querying songs by score ranges, if an XCD chart is included then the plot function will crash with index_out_of_bound.
其实应该抓个XCD的图然后改一下main.py的649行就好了，但我太懒了直接强行
`level_box = level_list[m_type + min(int(inf_ver), len(level_list)-m_type-1)]` lolll
这样会把XCD强行显示成VVD，不过好歹可以plot。
有空的话可以考虑加上一下。非常感谢这个小工具，特别酷！
![error](https://user-images.githubusercontent.com/26119841/171665856-97ec222a-6c7c-4995-a15d-f3095ddd19bb.png)

**Comment by Nyanm** [comment]
fixed in pure code
